name: Backup

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every day at 12:00 UTC
    - cron: '0 12 * * *'

jobs:
  backupGit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: |
          ruby main.rb
      - uses: stefanzweifel/git-auto-commit-action@v5